### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by evgeniyprowork** [evgeniyprowork/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by damienasero** [comment]
I am an American investor, business tycoon, philanthropist, and the chairman and CEO of Berkshire Hathaway. I am considered one of the most successful investors in the world. I look at each company as a whole, so i choose stocks solely based on their overall potential as a company. Holding these stocks as a long-term play, I don't seek capital gain, but ownership in quality companies extremely capable of generating earnings. When i invest in a company, I am not concerned with whether the market will eventually recognize its worth. I am concerned with how well that company can make money as a business.

**Comment by evgeniyprowork** [comment]
<h2>Resume</h2>
<p>I am an American investor, business tycoon, philanthropist, and the chairman and CEO of Berkshire Hathaway. I am considered one of the most successful investors in the world. I look at each company as a whole, so i choose stocks solely based on their overall potential as a company. Holding these stocks as a long-term play, I don't seek capital gain, but ownership in quality companies extremely capable of generating earnings. When i invest in a company, I am not concerned with whether the market will eventually recognize its worth. I am concerned with how well that company can make money as a business.</p>
