### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by evgeniyprowork** [evgeniyprowork/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by damienasero** [comment]
**Warren Buffett contacts:**

- https://www.instagram.com/officialwarrenbuffett/
- https://www.facebook.com/warren.bafet
- https://twitter.com/warrenbuffett
- berkshire@berkshirehathaway.com
- Berkshire Hathaway Inc., 3555 Farnam Street, Suite 1440, Omaha, NE 68131, USA

**Comment by evgeniyprowork** [comment]
**Warren Buffett**
**Job: investor** 
- https://www.instagram.com/officialwarrenbuffett/
- https://www.facebook.com/warren.bafet
- https://twitter.com/warrenbuffett
- berkshire@berkshirehathaway.com
- Berkshire Hathaway Inc., 3555 Farnam Street, Suite 1440, Omaha, NE 68131, USA
